CREATE DATABASE IF NOT EXISTS wordpressdb;

CREATE USER wordpressuser IDENTIFIED BY 'password';

GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpressdb.* TO wordpressuser;

FLUSH PRIVILEGES;